# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 605)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/quadcopter.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks | QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(7, 7, 7, 7)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_robots = QtWidgets.QTableWidget(self.groupBox)
        self.table_robots.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_robots.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_robots.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_robots.setColumnCount(3)
        self.table_robots.setObjectName("table_robots")
        self.table_robots.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_robots.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_robots.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_robots.setHorizontalHeaderItem(2, item)
        self.table_robots.horizontalHeader().setCascadingSectionResizes(True)
        self.table_robots.horizontalHeader().setHighlightSections(False)
        self.table_robots.horizontalHeader().setMinimumSectionSize(0)
        self.table_robots.horizontalHeader().setStretchLastSection(True)
        self.table_robots.verticalHeader().setVisible(False)
        self.table_robots.verticalHeader().setDefaultSectionSize(24)
        self.horizontalLayout.addWidget(self.table_robots)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_add_robot = QtWidgets.QToolButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_robot.setIcon(icon1)
        self.button_add_robot.setObjectName("button_add_robot")
        self.verticalLayout_2.addWidget(self.button_add_robot)
        self.button_edit_robot = QtWidgets.QToolButton(self.groupBox)
        self.button_edit_robot.setObjectName("button_edit_robot")
        self.verticalLayout_2.addWidget(self.button_edit_robot)
        self.button_remove_robot = QtWidgets.QToolButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../src/assert/substract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_remove_robot.setIcon(icon2)
        self.button_remove_robot.setObjectName("button_remove_robot")
        self.verticalLayout_2.addWidget(self.button_remove_robot)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table_batteries = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_batteries.setEnabled(True)
        self.table_batteries.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_batteries.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_batteries.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_batteries.setColumnCount(4)
        self.table_batteries.setObjectName("table_batteries")
        self.table_batteries.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_batteries.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_batteries.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_batteries.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_batteries.setHorizontalHeaderItem(3, item)
        self.table_batteries.horizontalHeader().setVisible(True)
        self.table_batteries.horizontalHeader().setCascadingSectionResizes(True)
        self.table_batteries.horizontalHeader().setDefaultSectionSize(60)
        self.table_batteries.horizontalHeader().setHighlightSections(False)
        self.table_batteries.horizontalHeader().setMinimumSectionSize(0)
        self.table_batteries.horizontalHeader().setStretchLastSection(True)
        self.table_batteries.verticalHeader().setVisible(False)
        self.table_batteries.verticalHeader().setDefaultSectionSize(24)
        self.horizontalLayout_2.addWidget(self.table_batteries)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_add_battery = QtWidgets.QToolButton(self.groupBox_2)
        self.button_add_battery.setIcon(icon1)
        self.button_add_battery.setObjectName("button_add_battery")
        self.verticalLayout_3.addWidget(self.button_add_battery)
        self.button_edit_battery = QtWidgets.QToolButton(self.groupBox_2)
        self.button_edit_battery.setObjectName("button_edit_battery")
        self.verticalLayout_3.addWidget(self.button_edit_battery)
        self.button_remove_battery = QtWidgets.QToolButton(self.groupBox_2)
        self.button_remove_battery.setIcon(icon2)
        self.button_remove_battery.setObjectName("button_remove_battery")
        self.verticalLayout_3.addWidget(self.button_remove_battery)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.table_dives = QtWidgets.QTableWidget(self.groupBox_3)
        self.table_dives.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_dives.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_dives.setAlternatingRowColors(True)
        self.table_dives.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_dives.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_dives.setObjectName("table_dives")
        self.table_dives.setColumnCount(6)
        self.table_dives.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_dives.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dives.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dives.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dives.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dives.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dives.setHorizontalHeaderItem(5, item)
        self.table_dives.horizontalHeader().setCascadingSectionResizes(True)
        self.table_dives.horizontalHeader().setDefaultSectionSize(120)
        self.table_dives.horizontalHeader().setHighlightSections(False)
        self.table_dives.horizontalHeader().setMinimumSectionSize(0)
        self.table_dives.horizontalHeader().setSortIndicatorShown(False)
        self.table_dives.horizontalHeader().setStretchLastSection(True)
        self.table_dives.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.table_dives)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_add_dive = QtWidgets.QToolButton(self.groupBox_3)
        self.button_add_dive.setIcon(icon1)
        self.button_add_dive.setObjectName("button_add_dive")
        self.verticalLayout_4.addWidget(self.button_add_dive)
        self.button_remove_dive = QtWidgets.QToolButton(self.groupBox_3)
        self.button_remove_dive.setIcon(icon2)
        self.button_remove_dive.setObjectName("button_remove_dive")
        self.verticalLayout_4.addWidget(self.button_remove_dive)
        self.button_stop_dive = QtWidgets.QToolButton(self.groupBox_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../src/assert/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_stop_dive.setIcon(icon3)
        self.button_stop_dive.setObjectName("button_stop_dive")
        self.verticalLayout_4.addWidget(self.button_stop_dive)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.button_refresh.setObjectName("button_refresh")
        self.horizontalLayout_3.addWidget(self.button_refresh)
        self.button_start_dive = QtWidgets.QPushButton(self.centralwidget)
        self.button_start_dive.setObjectName("button_start_dive")
        self.horizontalLayout_3.addWidget(self.button_start_dive)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 22))
        self.menubar.setObjectName("menubar")
        self.menuFi_e = QtWidgets.QMenu(self.menubar)
        self.menuFi_e.setObjectName("menuFi_e")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFi_e.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.table_robots, self.button_add_robot)
        MainWindow.setTabOrder(self.button_add_robot, self.button_edit_robot)
        MainWindow.setTabOrder(self.button_edit_robot, self.table_batteries)
        MainWindow.setTabOrder(self.table_batteries, self.button_add_battery)
        MainWindow.setTabOrder(self.button_add_battery, self.button_edit_battery)
        MainWindow.setTabOrder(self.button_edit_battery, self.table_dives)
        MainWindow.setTabOrder(self.table_dives, self.button_add_dive)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Battery Control"))
        item = self.table_robots.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Robot ID"))
        item = self.table_robots.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Robot name"))
        item = self.table_robots.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total time used"))
        self.button_add_robot.setText(_translate("MainWindow", "..."))
        self.button_edit_robot.setText(_translate("MainWindow", "..."))
        self.button_remove_robot.setText(_translate("MainWindow", "..."))
        item = self.table_batteries.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Battery ID"))
        item = self.table_batteries.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_batteries.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Voltage"))
        item = self.table_batteries.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total time used"))
        self.button_add_battery.setText(_translate("MainWindow", "..."))
        self.button_edit_battery.setText(_translate("MainWindow", "..."))
        self.button_remove_battery.setText(_translate("MainWindow", "..."))
        item = self.table_dives.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Dive ID"))
        item = self.table_dives.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Robot"))
        item = self.table_dives.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time Started"))
        item = self.table_dives.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time Finished"))
        item = self.table_dives.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.table_dives.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Batteries"))
        self.button_add_dive.setText(_translate("MainWindow", "..."))
        self.button_remove_dive.setText(_translate("MainWindow", "..."))
        self.button_stop_dive.setText(_translate("MainWindow", "..."))
        self.button_refresh.setText(_translate("MainWindow", "Refresh"))
        self.button_start_dive.setText(_translate("MainWindow", "Start new dive"))
        self.menuFi_e.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))

